/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PitchDeckRouteImport } from './routes/pitch-deck'
import { Route as FluxRouteImport } from './routes/flux'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForRealEstateRouteImport } from './routes/for/real-estate'
import { Route as BlogSolvingTheAgentMemoryProblemRouteImport } from './routes/blog/solving-the-agent-memory-problem'
import { Route as ForRealEstatePropertyPdfRouteImport } from './routes/for/real-estate_.property-pdf'

const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchDeckRoute = PitchDeckRouteImport.update({
  id: '/pitch-deck',
  path: '/pitch-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxRoute = FluxRouteImport.update({
  id: '/flux',
  path: '/flux',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRealEstateRoute = ForRealEstateRouteImport.update({
  id: '/for/real-estate',
  path: '/for/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSolvingTheAgentMemoryProblemRoute =
  BlogSolvingTheAgentMemoryProblemRouteImport.update({
    id: '/solving-the-agent-memory-problem',
    path: '/solving-the-agent-memory-problem',
    getParentRoute: () => BlogRoute,
  } as any)
const ForRealEstatePropertyPdfRoute =
  ForRealEstatePropertyPdfRouteImport.update({
    id: '/for/real-estate_/property-pdf',
    path: '/for/real-estate/property-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/blog': typeof BlogRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/flux': typeof FluxRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
  '/blog/solving-the-agent-memory-problem': typeof BlogSolvingTheAgentMemoryProblemRoute
  '/for/real-estate': typeof ForRealEstateRoute
  '/for/real-estate/property-pdf': typeof ForRealEstatePropertyPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/blog': typeof BlogRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/flux': typeof FluxRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
  '/blog/solving-the-agent-memory-problem': typeof BlogSolvingTheAgentMemoryProblemRoute
  '/for/real-estate': typeof ForRealEstateRoute
  '/for/real-estate/property-pdf': typeof ForRealEstatePropertyPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/blog': typeof BlogRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/flux': typeof FluxRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
  '/blog/solving-the-agent-memory-problem': typeof BlogSolvingTheAgentMemoryProblemRoute
  '/for/real-estate': typeof ForRealEstateRoute
  '/for/real-estate_/property-pdf': typeof ForRealEstatePropertyPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/blog'
    | '/cookie-policy'
    | '/flux'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
    | '/blog/solving-the-agent-memory-problem'
    | '/for/real-estate'
    | '/for/real-estate/property-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/blog'
    | '/cookie-policy'
    | '/flux'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
    | '/blog/solving-the-agent-memory-problem'
    | '/for/real-estate'
    | '/for/real-estate/property-pdf'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/blog'
    | '/cookie-policy'
    | '/flux'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
    | '/blog/solving-the-agent-memory-problem'
    | '/for/real-estate'
    | '/for/real-estate_/property-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  BlogRoute: typeof BlogRouteWithChildren
  CookiePolicyRoute: typeof CookiePolicyRoute
  FluxRoute: typeof FluxRoute
  PitchDeckRoute: typeof PitchDeckRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UniverseRoute: typeof UniverseRoute
  ForRealEstateRoute: typeof ForRealEstateRoute
  ForRealEstatePropertyPdfRoute: typeof ForRealEstatePropertyPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch-deck': {
      id: '/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/pitch-deck'
      preLoaderRoute: typeof PitchDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flux': {
      id: '/flux'
      path: '/flux'
      fullPath: '/flux'
      preLoaderRoute: typeof FluxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/real-estate': {
      id: '/for/real-estate'
      path: '/for/real-estate'
      fullPath: '/for/real-estate'
      preLoaderRoute: typeof ForRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/solving-the-agent-memory-problem': {
      id: '/blog/solving-the-agent-memory-problem'
      path: '/solving-the-agent-memory-problem'
      fullPath: '/blog/solving-the-agent-memory-problem'
      preLoaderRoute: typeof BlogSolvingTheAgentMemoryProblemRouteImport
      parentRoute: typeof BlogRoute
    }
    '/for/real-estate_/property-pdf': {
      id: '/for/real-estate_/property-pdf'
      path: '/for/real-estate/property-pdf'
      fullPath: '/for/real-estate/property-pdf'
      preLoaderRoute: typeof ForRealEstatePropertyPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSolvingTheAgentMemoryProblemRoute: typeof BlogSolvingTheAgentMemoryProblemRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSolvingTheAgentMemoryProblemRoute: BlogSolvingTheAgentMemoryProblemRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  BlogRoute: BlogRouteWithChildren,
  CookiePolicyRoute: CookiePolicyRoute,
  FluxRoute: FluxRoute,
  PitchDeckRoute: PitchDeckRoute,
  PrivacyRoute: PrivacyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UniverseRoute: UniverseRoute,
  ForRealEstateRoute: ForRealEstateRoute,
  ForRealEstatePropertyPdfRoute: ForRealEstatePropertyPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
