/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PitchDeckRouteImport } from './routes/pitch-deck'
import { Route as IsoStep2RouteImport } from './routes/iso-step2'
import { Route as IsoLabRouteImport } from './routes/iso-lab'
import { Route as HowItWorksLabRouteImport } from './routes/how-it-works-lab'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrandkitRouteImport } from './routes/brandkit'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalsIndexRouteImport } from './routes/signals.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as SignalsSolvingTheAgentMemoryProblemRouteImport } from './routes/signals/solving-the-agent-memory-problem'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers_.$slug'
import { Route as ApiJobApplicationRouteImport } from './routes/api.job-application'
import { Route as ApiCareerApplicationsRouteImport } from './routes/api.career-applications'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchDeckRoute = PitchDeckRouteImport.update({
  id: '/pitch-deck',
  path: '/pitch-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const IsoStep2Route = IsoStep2RouteImport.update({
  id: '/iso-step2',
  path: '/iso-step2',
  getParentRoute: () => rootRouteImport,
} as any)
const IsoLabRoute = IsoLabRouteImport.update({
  id: '/iso-lab',
  path: '/iso-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksLabRoute = HowItWorksLabRouteImport.update({
  id: '/how-it-works-lab',
  path: '/how-it-works-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandkitRoute = BrandkitRouteImport.update({
  id: '/brandkit',
  path: '/brandkit',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsSolvingTheAgentMemoryProblemRoute =
  SignalsSolvingTheAgentMemoryProblemRouteImport.update({
    id: '/signals/solving-the-agent-memory-problem',
    path: '/signals/solving-the-agent-memory-problem',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers_/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobApplicationRoute = ApiJobApplicationRouteImport.update({
  id: '/api/job-application',
  path: '/api/job-application',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareerApplicationsRoute = ApiCareerApplicationsRouteImport.update({
  id: '/api/career-applications',
  path: '/api/career-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/admin/careers',
  path: '/admin/careers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/brandkit': typeof BrandkitRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/download': typeof DownloadRoute
  '/how-it-works-lab': typeof HowItWorksLabRoute
  '/iso-lab': typeof IsoLabRoute
  '/iso-step2': typeof IsoStep2Route
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/api/career-applications': typeof ApiCareerApplicationsRoute
  '/api/job-application': typeof ApiJobApplicationRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/signals/solving-the-agent-memory-problem': typeof SignalsSolvingTheAgentMemoryProblemRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/signals/': typeof SignalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/brandkit': typeof BrandkitRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/download': typeof DownloadRoute
  '/how-it-works-lab': typeof HowItWorksLabRoute
  '/iso-lab': typeof IsoLabRoute
  '/iso-step2': typeof IsoStep2Route
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/api/career-applications': typeof ApiCareerApplicationsRoute
  '/api/job-application': typeof ApiJobApplicationRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/signals/solving-the-agent-memory-problem': typeof SignalsSolvingTheAgentMemoryProblemRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/signals': typeof SignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/brandkit': typeof BrandkitRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/download': typeof DownloadRoute
  '/how-it-works-lab': typeof HowItWorksLabRoute
  '/iso-lab': typeof IsoLabRoute
  '/iso-step2': typeof IsoStep2Route
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/api/career-applications': typeof ApiCareerApplicationsRoute
  '/api/job-application': typeof ApiJobApplicationRoute
  '/careers_/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/signals/solving-the-agent-memory-problem': typeof SignalsSolvingTheAgentMemoryProblemRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/signals/': typeof SignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/acceptable-use'
    | '/brandkit'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/download'
    | '/how-it-works-lab'
    | '/iso-lab'
    | '/iso-step2'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/admin/careers'
    | '/api/career-applications'
    | '/api/job-application'
    | '/careers/$slug'
    | '/industries/$slug'
    | '/signals/solving-the-agent-memory-problem'
    | '/solutions/$slug'
    | '/signals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/acceptable-use'
    | '/brandkit'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/download'
    | '/how-it-works-lab'
    | '/iso-lab'
    | '/iso-step2'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/admin/careers'
    | '/api/career-applications'
    | '/api/job-application'
    | '/careers/$slug'
    | '/industries/$slug'
    | '/signals/solving-the-agent-memory-problem'
    | '/solutions/$slug'
    | '/signals'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/acceptable-use'
    | '/brandkit'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/download'
    | '/how-it-works-lab'
    | '/iso-lab'
    | '/iso-step2'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/admin/careers'
    | '/api/career-applications'
    | '/api/job-application'
    | '/careers_/$slug'
    | '/industries/$slug'
    | '/signals/solving-the-agent-memory-problem'
    | '/solutions/$slug'
    | '/signals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  BrandkitRoute: typeof BrandkitRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DownloadRoute: typeof DownloadRoute
  HowItWorksLabRoute: typeof HowItWorksLabRoute
  IsoLabRoute: typeof IsoLabRoute
  IsoStep2Route: typeof IsoStep2Route
  PitchDeckRoute: typeof PitchDeckRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  ApiCareerApplicationsRoute: typeof ApiCareerApplicationsRoute
  ApiJobApplicationRoute: typeof ApiJobApplicationRoute
  CareersSlugRoute: typeof CareersSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  SignalsSolvingTheAgentMemoryProblemRoute: typeof SignalsSolvingTheAgentMemoryProblemRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch-deck': {
      id: '/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/pitch-deck'
      preLoaderRoute: typeof PitchDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iso-step2': {
      id: '/iso-step2'
      path: '/iso-step2'
      fullPath: '/iso-step2'
      preLoaderRoute: typeof IsoStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iso-lab': {
      id: '/iso-lab'
      path: '/iso-lab'
      fullPath: '/iso-lab'
      preLoaderRoute: typeof IsoLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works-lab': {
      id: '/how-it-works-lab'
      path: '/how-it-works-lab'
      fullPath: '/how-it-works-lab'
      preLoaderRoute: typeof HowItWorksLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brandkit': {
      id: '/brandkit'
      path: '/brandkit'
      fullPath: '/brandkit'
      preLoaderRoute: typeof BrandkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/signals'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/solving-the-agent-memory-problem': {
      id: '/signals/solving-the-agent-memory-problem'
      path: '/signals/solving-the-agent-memory-problem'
      fullPath: '/signals/solving-the-agent-memory-problem'
      preLoaderRoute: typeof SignalsSolvingTheAgentMemoryProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers_/$slug': {
      id: '/careers_/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job-application': {
      id: '/api/job-application'
      path: '/api/job-application'
      fullPath: '/api/job-application'
      preLoaderRoute: typeof ApiJobApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/career-applications': {
      id: '/api/career-applications'
      path: '/api/career-applications'
      fullPath: '/api/career-applications'
      preLoaderRoute: typeof ApiCareerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/admin/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  BrandkitRoute: BrandkitRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DownloadRoute: DownloadRoute,
  HowItWorksLabRoute: HowItWorksLabRoute,
  IsoLabRoute: IsoLabRoute,
  IsoStep2Route: IsoStep2Route,
  PitchDeckRoute: PitchDeckRoute,
  PrivacyRoute: PrivacyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AdminCareersRoute: AdminCareersRoute,
  ApiCareerApplicationsRoute: ApiCareerApplicationsRoute,
  ApiJobApplicationRoute: ApiJobApplicationRoute,
  CareersSlugRoute: CareersSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  SignalsSolvingTheAgentMemoryProblemRoute:
    SignalsSolvingTheAgentMemoryProblemRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SignalsIndexRoute: SignalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
