/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PitchDeckRouteImport } from './routes/pitch-deck'
import { Route as FluxRouteImport } from './routes/flux'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalsIndexRouteImport } from './routes/signals.index'
import { Route as SignalsSolvingTheAgentMemoryProblemRouteImport } from './routes/signals/solving-the-agent-memory-problem'
import { Route as ForRealEstateRouteImport } from './routes/for/real-estate'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as ForRealEstatePropertyPdfRouteImport } from './routes/for/real-estate_.property-pdf'

const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchDeckRoute = PitchDeckRouteImport.update({
  id: '/pitch-deck',
  path: '/pitch-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxRoute = FluxRouteImport.update({
  id: '/flux',
  path: '/flux',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsSolvingTheAgentMemoryProblemRoute =
  SignalsSolvingTheAgentMemoryProblemRouteImport.update({
    id: '/signals/solving-the-agent-memory-problem',
    path: '/signals/solving-the-agent-memory-problem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForRealEstateRoute = ForRealEstateRouteImport.update({
  id: '/for/real-estate',
  path: '/for/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/admin/careers',
  path: '/admin/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRealEstatePropertyPdfRoute =
  ForRealEstatePropertyPdfRouteImport.update({
    id: '/for/real-estate_/property-pdf',
    path: '/for/real-estate/property-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/careers': typeof CareersRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/download': typeof DownloadRoute
  '/flux': typeof FluxRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
  '/admin/careers': typeof AdminCareersRoute
  '/for/real-estate': typeof ForRealEstateRoute
  '/signals/solving-the-agent-memory-problem': typeof SignalsSolvingTheAgentMemoryProblemRoute
  '/signals/': typeof SignalsIndexRoute
  '/for/real-estate/property-pdf': typeof ForRealEstatePropertyPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/careers': typeof CareersRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/download': typeof DownloadRoute
  '/flux': typeof FluxRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
  '/admin/careers': typeof AdminCareersRoute
  '/for/real-estate': typeof ForRealEstateRoute
  '/signals/solving-the-agent-memory-problem': typeof SignalsSolvingTheAgentMemoryProblemRoute
  '/signals': typeof SignalsIndexRoute
  '/for/real-estate/property-pdf': typeof ForRealEstatePropertyPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/careers': typeof CareersRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/download': typeof DownloadRoute
  '/flux': typeof FluxRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
  '/admin/careers': typeof AdminCareersRoute
  '/for/real-estate': typeof ForRealEstateRoute
  '/signals/solving-the-agent-memory-problem': typeof SignalsSolvingTheAgentMemoryProblemRoute
  '/signals/': typeof SignalsIndexRoute
  '/for/real-estate_/property-pdf': typeof ForRealEstatePropertyPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/careers'
    | '/cookie-policy'
    | '/download'
    | '/flux'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
    | '/admin/careers'
    | '/for/real-estate'
    | '/signals/solving-the-agent-memory-problem'
    | '/signals/'
    | '/for/real-estate/property-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/careers'
    | '/cookie-policy'
    | '/download'
    | '/flux'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
    | '/admin/careers'
    | '/for/real-estate'
    | '/signals/solving-the-agent-memory-problem'
    | '/signals'
    | '/for/real-estate/property-pdf'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/careers'
    | '/cookie-policy'
    | '/download'
    | '/flux'
    | '/pitch-deck'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
    | '/admin/careers'
    | '/for/real-estate'
    | '/signals/solving-the-agent-memory-problem'
    | '/signals/'
    | '/for/real-estate_/property-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  CareersRoute: typeof CareersRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DownloadRoute: typeof DownloadRoute
  FluxRoute: typeof FluxRoute
  PitchDeckRoute: typeof PitchDeckRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UniverseRoute: typeof UniverseRoute
  AdminCareersRoute: typeof AdminCareersRoute
  ForRealEstateRoute: typeof ForRealEstateRoute
  SignalsSolvingTheAgentMemoryProblemRoute: typeof SignalsSolvingTheAgentMemoryProblemRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
  ForRealEstatePropertyPdfRoute: typeof ForRealEstatePropertyPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch-deck': {
      id: '/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/pitch-deck'
      preLoaderRoute: typeof PitchDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flux': {
      id: '/flux'
      path: '/flux'
      fullPath: '/flux'
      preLoaderRoute: typeof FluxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/signals'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/solving-the-agent-memory-problem': {
      id: '/signals/solving-the-agent-memory-problem'
      path: '/signals/solving-the-agent-memory-problem'
      fullPath: '/signals/solving-the-agent-memory-problem'
      preLoaderRoute: typeof SignalsSolvingTheAgentMemoryProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/real-estate': {
      id: '/for/real-estate'
      path: '/for/real-estate'
      fullPath: '/for/real-estate'
      preLoaderRoute: typeof ForRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/admin/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/real-estate_/property-pdf': {
      id: '/for/real-estate_/property-pdf'
      path: '/for/real-estate/property-pdf'
      fullPath: '/for/real-estate/property-pdf'
      preLoaderRoute: typeof ForRealEstatePropertyPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  CareersRoute: CareersRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DownloadRoute: DownloadRoute,
  FluxRoute: FluxRoute,
  PitchDeckRoute: PitchDeckRoute,
  PrivacyRoute: PrivacyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UniverseRoute: UniverseRoute,
  AdminCareersRoute: AdminCareersRoute,
  ForRealEstateRoute: ForRealEstateRoute,
  SignalsSolvingTheAgentMemoryProblemRoute:
    SignalsSolvingTheAgentMemoryProblemRoute,
  SignalsIndexRoute: SignalsIndexRoute,
  ForRealEstatePropertyPdfRoute: ForRealEstatePropertyPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
